version: "3.7"

services:
  callg-client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "8002:8002"
    environment:
      - CHOKIDAR_USEPOLLING=true

    networks:
      - callg-client

networks:
  callg-client:
    driver: bridge
    name: callg
