version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - type: bind
        source: ./
        target: /app
        read_only: true
      - exclude:/app/node_modules/
    ports:
      - "8002:8002"
    environment:
      - CHOKIDAR_USEPOLLING=true

    networks:
      - callg
networks:
  callg:
    driver: bridge
    name: callg

volumes:
  exclude:
